# Generated by Django 4.0.4 on 2022-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_date_articles_timestamp_articles_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articles',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
