# Generated by Django 4.0.4 on 2022-06-07 12:13

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('year', models.DateField(unique_for_year=True)),
                ('capacity', models.FloatField()),
                ('transmission', models.CharField(max_length=100)),
                ('engine_type', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=100)),
                ('image', models.ImageField(height_field='height_field', null=True, upload_to=mainApp.models.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.brand')),
            ],
        ),
    ]
