# Generated by Django 4.0.4 on 2022-06-07 14:09

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_car_height_field_alter_car_width_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='car',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=mainApp.models.upload_location),
        ),
    ]
