# Generated by Django 4.0.4 on 2022-06-07 14:33

from django.db import migrations, models
import mainApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_car_capacity_alter_car_price_alter_car_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=mainApp.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='car',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
